name: Docs CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches: [ "main" ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            README.md
            docs/**/*.md
            examples/**/*.md
          config: .markdownlint-cli2.jsonc
    continue-on-error: true
